solve: Diagonal Difference

diff --git a/hackerrank/Makefile b/hackerrank/Makefile
--- a/hackerrank/Makefile
+++ b/hackerrank/Makefile
@@ -8,4 +8,4 @@ test: solution
 	@expected="$(shell cat output.txt)"; \
 	got="$(shell export OUTPUT_PATH=/dev/stdout; cat input.txt | ./$^)"; \
 	test "$$expected" = "$$got" && \
-	echo "Pass!" || (echo "Fail! Expected $$expected, got $$got" && exit 1)
+	echo "\e[32mPass!\e[0m" || (echo "\e[31mFail! Expected $$expected, got $$got\e[0m" && exit 1)
